baseURL = "https://lucaslbrugger.github.io/quantum_stuff/"
title = "Quantum Stuff Group"

buildFuture = true

[params]
    description = "Grupo de pesquisa em Física e em Fundamentos de Mecânica Quântica da Universidade Federal de Juiz de Fora."